### ISSUE TITLE
Issues with xterm-color-chooser

### ISSUE THREAD

**Issue by ied206** [grawity/code#2]
## Symptoms

[xterm-color-chooser.py](https://github.com/grawity/code/blob/b241477d5aac9d0e028d6393d58696c0eea531a5/term/xterm-color-chooser) crashes on some conditions:

### 1. Switching to other color modes
Pressing g/G to switch between color modes crashes the script.

```console
Traceback (most recent call last):
  File "./xterm-color-chooser", line 565, in <module>
    while main(state):
  File "./xterm-color-chooser", line 385, in main
    line += "\033[49m" + state.fmt() + char*20 + "\033[m│"
  File "./xterm-color-chooser", line 304, in fmt
    color = self.getcolor()
  File "./xterm-color-chooser", line 213, in getcolor
    return self["color"] + self["bright"]*8
KeyError: 'bright'
```

I suspect that this happens only on fresh new machine, as it may not have persistent state with `bright` key.

#### Solution

Inserting `self["bright"] = 0` into `State.init(self)` solves the problem.

### 2. Unable to load persistent state

After crashing due to the `self["bright"]`, the persistent state gets garbled. At this stage, the script just refuses to run. 

```console
Traceback (most recent call last):
  File "./xterm-color-chooser", line 557, in <module>
    state.load_persistent()
  File "./xterm-color-chooser", line 102, in load_persistent
    self.load(json.load(fh))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

#### Solution

The state loading mechanism needs some fail-safe.

### Suggestion for Python 2.x support

By the way, the script runs well on python 2 by inserting `from __future__ import print_function`. It would be useful for limited environments (e.g. Default CentOS 6 installation without root privilege).

**Comment by grawity** [comment]
Thanks, I've fixed the issues – the `"bright"` key was a very recent addition and I overlooked its initialization on empty state.

I really don't want to "officially" advertise Python 2 compatibility though, even if it happens to still work. (Switching to python3-only was deliberate; the script uses FileNotFoundError which does not exist in Py2.)

**Comment by ied206** [comment]
Thank you about the fix. I understand your decision about the Python 2 support, as its lifespan is over.
