### ISSUE TITLE
How to use getpaste fot add privatebin with debian and use it with console

### ISSUE THREAD

**Issue by ZerooCool** [grawity/code#3]
How to use getpaste fot add privatebin with debian and use it with console

I want export logfile, to my privatebin instance.
Can you explain if i can make that, with your code, and, the best method ?

https://github.com/grawity/code/blob/master/net/getpaste

Thank you.

**Comment by grawity** [comment]
getpaste cannot do this; it is a tool for _downloading_ pastebin posts only.

If you need to upload, see [PrivateBin's list of clients](https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients).

**Comment by ZerooCool** [comment]
Ok i look that
